# Google Cloud Function deployment configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: waste-sorting-config
data:
  runtime: go121
  entry_point: ProcessWasteImage
  memory: 512Mi
  timeout: 60s
  max_instances: 100
  
  # Environment variables (set these in Cloud Console or via gcloud)
  # GOOGLE_CLOUD_PROJECT: "your-project-id"
  # RECAPTCHA_SITE_KEY: "your-recaptcha-site-key" 
  # GEMINI_API_KEY: "your-gemini-api-key"

---
# Example gcloud deployment command:
# gcloud functions deploy waste-sorting-api \
#   --gen2 \
#   --runtime=go121 \
#   --region=europe-west1 \
#   --source=. \
#   --entry-point=ProcessWasteImage \
#   --trigger=http \
#   --allow-unauthenticated \
#   --memory=512Mi \
#   --timeout=60s \
#   --max-instances=100 \
#   --set-env-vars="GOOGLE_CLOUD_PROJECT=your-project-id,RECAPTCHA_SITE_KEY=your-key,GEMINI_API_KEY=your-key"